#include "DX12DrawSet.h"
#include "DX12RenderClasses.h"
#include <d3dx12.h>

D3D12_STATIC_SAMPLER_DESC DX12DrawSet::m_StaticSamplers[7] =
{
	CD3DX12_STATIC_SAMPLER_DESC(
	0,
	D3D12_FILTER_MIN_MAG_MIP_POINT,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP),

	CD3DX12_STATIC_SAMPLER_DESC(
	1,
	D3D12_FILTER_MIN_MAG_MIP_POINT,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP),

	CD3DX12_STATIC_SAMPLER_DESC(
	2,
	D3D12_FILTER_MIN_MAG_MIP_LINEAR,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP),

	CD3DX12_STATIC_SAMPLER_DESC(
	3,
	D3D12_FILTER_MIN_MAG_MIP_LINEAR,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP),

	CD3DX12_STATIC_SAMPLER_DESC(
	4,
	D3D12_FILTER_ANISOTROPIC,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	0.0f,
	8),

	CD3DX12_STATIC_SAMPLER_DESC(
	5,
	D3D12_FILTER_ANISOTROPIC,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	0.0f,
	8),

	 CD3DX12_STATIC_SAMPLER_DESC(
	6,
	D3D12_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT,
	D3D12_TEXTURE_ADDRESS_MODE_BORDER,
	D3D12_TEXTURE_ADDRESS_MODE_BORDER,
	D3D12_TEXTURE_ADDRESS_MODE_BORDER,
	0.0f,
	16,
	D3D12_COMPARISON_FUNC_LESS_EQUAL,
	D3D12_STATIC_BORDER_COLOR_OPAQUE_BLACK)
};

void DX12DrawSet::UpdateFrameCount()
{
	m_CurrFrame = (m_CurrFrame + 1) % m_NumFrame;
}

D3D12_GPU_VIRTUAL_ADDRESS DX12DrawSet::GetCurrMainPassAddress() const
{
	static unsigned int mainPassStride= (sizeof(PassConstants) + 255) & ~255;

	return m_MainPassCB->GetGPUVirtualAddress() + (mainPassStride * m_CurrFrame);
}

void DX12DrawSet::SetPSO(ID3D12GraphicsCommandList* cmd)
{
	m_PSOCon->SetPSOToCommnadList(cmd, m_PSOA.rtvFormats, m_PSOA.dsvFormat,
		m_PSOA.primitive, m_PSOA.input, m_PSOA.rootSig, m_PSOA.rasterizer, m_PSOA.blend,
		m_PSOA.depthStencil, m_PSOA.vs, m_PSOA.ps, m_PSOA.gs, m_PSOA.hs, m_PSOA.ds);
}
